import { Montserrat, Poppins } from "next/font/google"
import "./globals.css";
import Sidenav from "../(tdashboard)/components/sidenav";

import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";


const getUserById = async (id: string| undefined) =>{
  try {
      const res = await fetch(`http://localhost:3000/api/user/${id}`, 
        {
          cache: 'no-store'
        }
      )
      return res.json()
      
  } catch (error) {
      console.log(error);
      
  }


}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Montserrat({
  weight: '400',
  subsets: ['latin'],
})

export default async  function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const {getUser} = getKindeServerSession()
  const user = await getUser()
  const z = await getUserById(user?.id)
  return (
    <html lang="en" className={poppins.className}>
      <body>
      <Sidenav x={user?.id.toString()  } detail={z.role === 'tutor'}/>
        {children}
        </body>
    </html>
  )
}
