import type { Metadata } from "next";
import Sidebar from "./admin_component/sidebar";
import { Poppins } from "next/font/google";

import "./adminglobals.css";
const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
       <div className='bigdiv'>
       <Sidebar/>
       {children}
       </div>
        </body>
    </html>
  );
}
