import type { Metadata } from "next";
import Sidebar from "./admin_component/sidebar";
import { Montserrat, Outfit, Poppins } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import "@uploadthing/react/styles.css";

import "./adminglobals.css";
import { ourFileRouter } from "../api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
const poppins = Outfit({
  weight: '400',
  subsets: ['latin'],
})

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
       <div className='bigdiv'>
       <Sidebar/>
       {children}
       </div>
        </body>
    </html>
  );
}
